server:
  port: 8080

spring:
  application:
    name: gateway-a1
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.http.server.reactive: DEBUG
    org.springframework.cloud.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false
