server:
  port: 8080

spring:
  application:
    name: gateway-a1
  cloud:
    gateway:
      # 使用 yml 方式配置路由规则
      routes:
        - id: baidu_route
          uri: http://www.baidu.com:80/
          predicates:
            - Path=/baidu
        - id: sina_route
          uri: http://www.sina.com.cn:80/
          predicates:
            - Path=/sina
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.http.server.reactive: DEBUG
    org.springframework.cloud.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

